import { Contact } from '../types/contact';
import { generateId } from './uuid';

const sampleContacts: Contact[] = [
  {
    id: generateId(),
    firstName: 'Adam',
    lastName: 'Smith',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 123-4567' }],
    emails: [{ id: generateId(), label: 'home', email: 'adam.smith@email.com' }],
    company: 'Tech Corp',
    jobTitle: 'Engineer',
    address: '123 Apple St, Cupertino, CA',
    notes: 'Met at WWDC 2024',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Brenda',
    lastName: 'Johnson',
    phones: [{ id: generateId(), label: 'work', number: '(555) 234-5678' }],
    emails: [{ id: generateId(), label: 'work', email: 'brenda.j@company.com' }],
    company: 'Design Studio',
    jobTitle: 'Designer',
    address: '456 Design Ave, San Francisco, CA',
    notes: '',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Charles',
    lastName: 'Williams',
    phones: [
      { id: generateId(), label: 'mobile', number: '(555) 345-6789' },
      { id: generateId(), label: 'home', number: '(555) 456-7890' },
    ],
    emails: [],
    company: '',
    jobTitle: '',
    address: '',
    notes: 'Best friend from college',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Diana',
    lastName: 'Brown',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 567-8901' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'diana@icloud.com' }],
    company: 'Apple Inc',
    jobTitle: 'Manager',
    address: 'One Apple Park Way, Cupertino, CA',
    notes: 'Colleague at work',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Edward',
    lastName: 'Davis',
    phones: [{ id: generateId(), label: 'work', number: '(555) 678-9012' }],
    emails: [
      { id: generateId(), label: 'home', email: 'edward.davis@email.com' },
      { id: generateId(), label: 'work', email: 'e.davis@company.com' },
    ],
    company: 'Startup Inc',
    jobTitle: 'CEO',
    address: '789 Innovation Blvd, Palo Alto, CA',
    notes: 'Investment advisor',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Fiona',
    lastName: 'Miller',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 789-0123' }],
    emails: [{ id: generateId(), label: 'home', email: 'fiona.m@email.com' }],
    company: '',
    jobTitle: '',
    address: '',
    notes: '',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'George',
    lastName: 'Wilson',
    phones: [{ id: generateId(), label: 'iphone', number: '(555) 890-1234' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'george.wilson@icloud.com' }],
    company: 'Fitness Center',
    jobTitle: 'Trainer',
    address: '321 Health St, Mountain View, CA',
    notes: 'Personal trainer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Hannah',
    lastName: 'Moore',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 901-2345' }],
    emails: [{ id: generateId(), label: 'work', email: 'hannah.m@tech.com' }],
    company: 'Google',
    jobTitle: 'PM',
    address: '1600 Amphitheatre Pkwy, Mountain View, CA',
    notes: 'Project manager',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Ian',
    lastName: 'Taylor',
    phones: [
      { id: generateId(), label: 'mobile', number: '(555) 012-3456' },
      { id: generateId(), label: 'fax', number: '(555) 111-2222' },
    ],
    emails: [{ id: generateId(), label: 'home', email: 'ian.taylor@email.com' }],
    company: 'Law Firm LLC',
    jobTitle: 'Attorney',
    address: '555 Legal Ave, San Jose, CA',
    notes: 'Family lawyer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Julia',
    lastName: 'Anderson',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 111-2223' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'julia.anderson@icloud.com' }],
    company: '',
    jobTitle: '',
    address: '',
    notes: 'Sister',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const createSampleContacts = (): Contact[] => {
  return sampleContacts;
};