import { Contact } from '../types/contact';
import { generateId } from './uuid';

const sampleContacts: Contact[] = [
  {
    id: generateId(),
    firstName: 'Adam',
    lastName: 'Smith',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 123-4567' }],
    emails: [{ id: generateId(), label: 'home', email: 'adam.smith@email.com' }],
    company: 'Tech Corp',
    address: '123 Apple St, Cupertino, CA',
    notes: 'Met at WWDC 2024',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Brenda',
    lastName: 'Johnson',
    phones: [{ id: generateId(), label: 'work', number: '(555) 234-5678' }],
    emails: [{ id: generateId(), label: 'work', email: 'brenda.j@company.com' }],
    company: 'Design Studio',
    address: '456 Design Ave, San Francisco, CA',
    notes: '',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Charles',
    lastName: 'Williams',
    phones: [
      { id: generateId(), label: 'mobile', number: '(555) 345-6789' },
      { id: generateId(), label: 'home', number: '(555) 456-7890' },
    ],
    emails: [],
    company: '',
    address: '',
    notes: 'Best friend from college',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Diana',
    lastName: 'Brown',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 567-8901' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'diana@icloud.com' }],
    company: 'Apple Inc',
    address: 'One Apple Park Way, Cupertino, CA',
    notes: 'Colleague at work',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Edward',
    lastName: 'Davis',
    phones: [{ id: generateId(), label: 'work', number: '(555) 678-9012' }],
    emails: [
      { id: generateId(), label: 'home', email: 'edward.davis@email.com' },
      { id: generateId(), label: 'work', email: 'e.davis@company.com' },
    ],
    company: 'Startup Inc',
    address: '789 Innovation Blvd, Palo Alto, CA',
    notes: 'Investment advisor',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Fiona',
    lastName: 'Miller',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 789-0123' }],
    emails: [{ id: generateId(), label: 'home', email: 'fiona.m@email.com' }],
    company: '',
    address: '',
    notes: '',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'George',
    lastName: 'Wilson',
    phones: [{ id: generateId(), label: 'iphone', number: '(555) 890-1234' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'george.wilson@icloud.com' }],
    company: 'Fitness Center',
    address: '321 Health St, Mountain View, CA',
    notes: 'Personal trainer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Hannah',
    lastName: 'Moore',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 901-2345' }],
    emails: [{ id: generateId(), label: 'work', email: 'hannah.m@tech.com' }],
    company: 'Google',
    address: '1600 Amphitheatre Pkwy, Mountain View, CA',
    notes: 'Project manager',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Ian',
    lastName: 'Taylor',
    phones: [
      { id: generateId(), label: 'mobile', number: '(555) 012-3456' },
      { id: generateId(), label: 'fax', number: '(555) 111-2222' },
    ],
    emails: [{ id: generateId(), label: 'home', email: 'ian.taylor@email.com' }],
    company: 'Law Firm LLC',
    address: '555 Legal Ave, San Jose, CA',
    notes: 'Family lawyer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Julia',
    lastName: 'Anderson',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 111-2223' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'julia.anderson@icloud.com' }],
    company: '',
    address: '',
    notes: 'Sister',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Kevin',
    lastName: 'Thomas',
    phones: [{ id: generateId(), label: 'work', number: '(555) 222-3334' }],
    emails: [{ id: generateId(), label: 'work', email: 'kevin.thomas@corp.com' }],
    company: 'Enterprise Solutions',
    address: '888 Business Park, Oakland, CA',
    notes: '',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Laura',
    lastName: 'Jackson',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 333-4445' }],
    emails: [{ id: generateId(), label: 'home', email: 'laura.jackson@email.com' }],
    company: '',
    address: '777 Residential Rd, Berkeley, CA',
    notes: 'Neighbor',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Michael',
    lastName: 'White',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 444-5556' }],
    emails: [{ id: generateId(), label: 'work', email: 'michael.white@startup.io' }],
    company: 'Tech Startup',
    address: '100 Innovation Lab, San Francisco, CA',
    notes: 'Co-founder',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Nancy',
    lastName: 'Harris',
    phones: [{ id: generateId(), label: 'home', number: '(555) 555-6667' }],
    emails: [{ id: generateId(), label: 'home', email: 'nancy.harris@email.com' }],
    company: '',
    address: '222 Family Home, Fremont, CA',
    notes: 'Aunt',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Oliver',
    lastName: 'Martin',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 666-7778' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'oliver.martin@icloud.com' }],
    company: 'Music Studio',
    address: '333 Sound Ave, Los Angeles, CA',
    notes: 'Music producer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Patricia',
    lastName: 'Garcia',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 777-8889' }],
    emails: [{ id: generateId(), label: 'work', email: 'patricia.g@marketing.com' }],
    company: 'Marketing Pro',
    address: '444 Brand St, Santa Monica, CA',
    notes: 'Marketing consultant',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Quinn',
    lastName: 'Rodriguez',
    phones: [{ id: generateId(), label: 'work', number: '(555) 888-9990' }],
    emails: [{ id: generateId(), label: 'work', email: 'quinn.r@finance.com' }],
    company: 'Finance Group',
    address: '666 Money Lane, New York, NY',
    notes: 'Financial advisor',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Rachel',
    lastName: 'Martinez',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 999-0001' }],
    emails: [{ id: generateId(), label: 'home', email: 'rachel.m@email.com' }],
    company: '',
    address: '777 Home Base, Austin, TX',
    notes: 'College roommate',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Samuel',
    lastName: 'Robinson',
    phones: [{ id: generateId(), label: 'iphone', number: '(555) 000-1112' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'sam.robinson@icloud.com' }],
    company: 'Apple Store',
    address: 'Apple Store, 1 Infinite Loop, Cupertino, CA',
    notes: 'Genius Bar appointment',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Tina',
    lastName: 'Clark',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 111-2223' }],
    emails: [{ id: generateId(), label: 'work', email: 'tina.clark@media.com' }],
    company: 'Media Corp',
    address: '888 Content Blvd, Los Angeles, CA',
    notes: 'Journalist',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Ulysses',
    lastName: 'Lewis',
    phones: [{ id: generateId(), label: 'work', number: '(555) 222-3334' }],
    emails: [{ id: generateId(), label: 'work', email: 'ulysses.l@engineering.com' }],
    company: 'Engineering Works',
    address: '999 Tech Dr, Seattle, WA',
    notes: 'Software architect',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Victoria',
    lastName: 'Lee',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 333-4445' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'victoria.lee@icloud.com' }],
    company: '',
    address: '111 Family House, Portland, OR',
    notes: 'Cousin',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'William',
    lastName: 'Walker',
    phones: [{ id: generateId(), label: 'home', number: '(555) 444-5556' }],
    emails: [{ id: generateId(), label: 'home', email: 'will.walker@email.com' }],
    company: '',
    address: '222 Suburb St, Denver, CO',
    notes: '',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Xena',
    lastName: 'Hall',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 555-6667' }],
    emails: [{ id: generateId(), label: 'work', email: 'xena.hall@creative.com' }],
    company: 'Creative Agency',
    address: '333 Art District, Miami, FL',
    notes: 'Graphic designer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Yusuf',
    lastName: 'Allen',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 666-7778' }],
    emails: [{ id: generateId(), label: 'home', email: 'yusuf.allen@email.com' }],
    company: 'Medical Center',
    address: '444 Health Plaza, Chicago, IL',
    notes: 'Family doctor',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Zara',
    lastName: 'Young',
    phones: [{ id: generateId(), label: 'iphone', number: '(555) 777-8889' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'zara.young@icloud.com' }],
    company: '',
    address: '555 College Ave, Boston, MA',
    notes: 'Grad school friend',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Albert',
    lastName: 'King',
    phones: [{ id: generateId(), label: 'work', number: '(555) 888-9990' }],
    emails: [{ id: generateId(), label: 'work', email: 'albert.king@consulting.com' }],
    company: 'Consulting Firm',
    address: '666 Business Center, Houston, TX',
    notes: 'Business consultant',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Beth',
    lastName: 'Wright',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 999-0001' }],
    emails: [{ id: generateId(), label: 'home', email: 'beth.wright@email.com' }],
    company: '',
    address: '777 Local St, Phoenix, AZ',
    notes: '',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Clark',
    lastName: 'Scott',
    phones: [{ id: generateId(), label: 'work', number: '(555) 000-1112' }],
    emails: [{ id: generateId(), label: 'work', email: 'clark.scott@legal.com' }],
    company: 'Legal Associates',
    address: '888 Court House Rd, Philadelphia, PA',
    notes: 'Attorney',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Diana',
    lastName: 'Green',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 111-2223' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'diana.green@icloud.com' }],
    company: 'Photography Studio',
    address: '999 Picture Lane, Nashville, TN',
    notes: 'Wedding photographer',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Eric',
    lastName: 'Adams',
    phones: [{ id: generateId(), label: 'home', number: '(555) 222-3334' }],
    emails: [{ id: generateId(), label: 'home', email: 'eric.adams@email.com' }],
    company: '',
    address: '111 Home Base, Orlando, FL',
    notes: 'Golf buddy',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Faye',
    lastName: 'Baker',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 333-4445' }],
    emails: [{ id: generateId(), label: 'work', email: 'faye.baker@education.com' }],
    company: 'University',
    address: '222 Campus Dr, Ann Arbor, MI',
    notes: 'Professor',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Greg',
    lastName: 'Nelson',
    phones: [{ id: generateId(), label: 'work', number: '(555) 444-5556' }],
    emails: [{ id: generateId(), label: 'work', email: 'greg.nelson@sales.com' }],
    company: 'Sales Force',
    address: '333 Revenue Rd, San Diego, CA',
    notes: 'Sales director',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Helen',
    lastName: 'Carter',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 555-6667' }],
    emails: [{ id: generateId(), label: 'home', email: 'helen.carter@email.com' }],
    company: '',
    address: '444 Family Home, Dallas, TX',
    notes: 'Mom friend',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Ivan',
    lastName: 'Mitchell',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 666-7778' }],
    emails: [{ id: generateId(), label: 'work', email: 'ivan.mitchell@tech.com' }],
    company: 'AI Research',
    address: '555 Innovation Way, Montreal, QC',
    notes: 'ML researcher',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Jenna',
    lastName: 'Perez',
    phones: [{ id: generateId(), label: 'iphone', number: '(555) 777-8889' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'jenna.perez@icloud.com' }],
    company: '',
    address: '666 Social Ave, Atlanta, GA',
    notes: 'Book club member',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Kyle',
    lastName: 'Roberts',
    phones: [{ id: generateId(), label: 'work', number: '(555) 888-9990' }],
    emails: [{ id: generateId(), label: 'work', email: 'kyle.roberts@corp.com' }],
    company: 'Corporate HQ',
    address: '777 Enterprise Blvd, Charlotte, NC',
    notes: 'VP of Engineering',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Lydia',
    lastName: 'Turner',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 999-0001' }],
    emails: [{ id: generateId(), label: 'home', email: 'lydia.turner@email.com' }],
    company: '',
    address: '888 Quiet Lane, Minneapolis, MN',
    notes: '',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Mark',
    lastName: 'Phillips',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 000-1112' }],
    emails: [{ id: generateId(), label: 'work', email: 'mark.phillips@hardware.com' }],
    company: 'Hardware Labs',
    address: '999 Chip St, Portland, OR',
    notes: 'Hardware engineer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Nina',
    lastName: 'Campbell',
    phones: [{ id: generateId(), label: 'home', number: '(555) 111-2223' }],
    emails: [{ id: generateId(), label: 'home', email: 'nina.campbell@email.com' }],
    company: '',
    address: '111 Cozy Home, Tampa, FL',
    notes: 'Knitting group',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Oscar',
    lastName: 'Parker',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 222-3334' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'oscar.parker@icloud.com' }],
    company: 'Film Studio',
    address: '222 Movie Blvd, Hollywood, CA',
    notes: 'Film director',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Paul',
    lastName: 'Evans',
    phones: [{ id: generateId(), label: 'work', number: '(555) 333-4445' }],
    emails: [{ id: generateId(), label: 'work', email: 'paul.evans@data.com' }],
    company: 'Data Systems',
    address: '333 Database Dr, Raleigh, NC',
    notes: 'Data scientist',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Queenie',
    lastName: 'Edwards',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 444-5556' }],
    emails: [{ id: generateId(), label: 'home', email: 'queenie.edwards@email.com' }],
    company: 'Restaurant',
    address: '444 Food Court, New Orleans, LA',
    notes: 'Chef',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Ryan',
    lastName: 'Collins',
    phones: [{ id: generateId(), label: 'iphone', number: '(555) 555-6667' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'ryan.collins@icloud.com' }],
    company: '',
    address: '555 Athletic Way, Boulder, CO',
    notes: 'Running partner',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Sarah',
    lastName: 'Stewart',
    phones: [{ id: generateId(), label: 'work', number: '(555) 666-7778' }],
    emails: [{ id: generateId(), label: 'work', email: 'sarah.stewart@pm.com' }],
    company: 'Product Management Inc',
    address: '666 Roadmap Ave, San Francisco, CA',
    notes: 'Senior PM',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Tom',
    lastName: 'Sanchez',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 777-8889' }],
    emails: [{ id: generateId(), label: 'home', email: 'tom.sanchez@email.com' }],
    company: '',
    address: '777 Soccer Field, Columbus, OH',
    notes: 'Soccer coach',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Uma',
    lastName: 'Morris',
    phones: [{ id: generateId(), label: 'work', number: '(555) 888-9990' }],
    emails: [{ id: generateId(), label: 'work', email: 'uma.morris@hr.com' }],
    company: 'HR Solutions',
    address: '888 People Plaza, Detroit, MI',
    notes: 'HR manager',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Victor',
    lastName: 'Rogers',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 999-0001' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'victor.rogers@icloud.com' }],
    company: '',
    address: '999 Gaming Ave, Austin, TX',
    notes: 'Gaming streamer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Wendy',
    lastName: 'Reed',
    phones: [{ id: generateId(), label: 'home', number: '(555) 000-1112' }],
    emails: [{ id: generateId(), label: 'home', email: 'wendy.reed@email.com' }],
    company: '',
    address: '111 Garden St, Portland, OR',
    notes: 'Gardening club',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Xavier',
    lastName: 'Cook',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 111-2223' }],
    emails: [{ id: generateId(), label: 'work', email: 'xavier.cook@security.com' }],
    company: 'Security Systems',
    address: '222 Safe St, Washington, DC',
    notes: 'Security consultant',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Yvonne',
    lastName: 'Morgan',
    phones: [{ id: generateId(), label: 'work', number: '(555) 222-3334' }],
    emails: [{ id: generateId(), label: 'work', email: 'yvonne.morgan@ops.com' }],
    company: 'Operations Co',
    address: '333 Logistics Ln, Memphis, TN',
    notes: 'Operations director',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Zach',
    lastName: 'Bell',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 333-4445' }],
    emails: [{ id: generateId(), label: 'home', email: 'zach.bell@email.com' }],
    company: '',
    address: '444 Lake View, Seattle, WA',
    notes: 'Fishing buddy',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Amy',
    lastName: 'Murphy',
    phones: [{ id: generateId(), label: 'iphone', number: '(555) 444-5556' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'amy.murphy@icloud.com' }],
    company: '',
    address: '555 Beach Rd, San Diego, CA',
    notes: 'Beach volleyball',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Bob',
    lastName: 'Kelly',
    phones: [{ id: generateId(), label: 'work', number: '(555) 555-6667' }],
    emails: [{ id: generateId(), label: 'work', email: 'bob.kelly@qa.com' }],
    company: 'Quality Assurance Inc',
    address: '666 Test Blvd, Kansas City, MO',
    notes: 'QA lead',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Carla',
    lastName: 'Simmons',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 666-7778' }],
    emails: [{ id: generateId(), label: 'home', email: 'carla.simmons@email.com' }],
    company: '',
    address: '777 Mountain View, Denver, CO',
    notes: 'Hiking club',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'David',
    lastName: 'Henry',
    phones: [{ id: generateId(), label: 'work', number: '(555) 777-8889' }],
    emails: [{ id: generateId(), label: 'work', email: 'david.henry@dev.com' }],
    company: 'DevOps Team',
    address: '888 Cloud St, Seattle, WA',
    notes: 'DevOps engineer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Emma',
    lastName: 'Campbell',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 888-9990' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'emma.campbell@icloud.com' }],
    company: 'Wellness Center',
    address: '999 Health Blvd, Santa Barbara, CA',
    notes: 'Yoga instructor',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Frank',
    lastName: 'Graham',
    phones: [{ id: generateId(), label: 'home', number: '(555) 999-0001' }],
    emails: [{ id: generateId(), label: 'home', email: 'frank.graham@email.com' }],
    company: '',
    address: '111 Vintage Ave, Savannah, GA',
    notes: 'Antique collector',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Grace',
    lastName: 'Henderson',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 000-1112' }],
    emails: [{ id: generateId(), label: 'work', email: 'grace.henderson@nonprofit.com' }],
    company: 'Non-Profit Org',
    address: '222 Charity Ct, Baltimore, MD',
    notes: 'Charity organizer',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Henry',
    lastName: 'Coleman',
    phones: [{ id: generateId(), label: 'work', number: '(555) 111-2223' }],
    emails: [{ id: generateId(), label: 'work', email: 'henry.coleman@finance.com' }],
    company: 'Financial Services',
    address: '333 Money Market, Boston, MA',
    notes: 'Investment banker',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Iris',
    lastName: 'Foster',
    phones: [{ id: generateId(), label: 'iphone', number: '(555) 222-3334' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'iris.foster@icloud.com' }],
    company: '',
    address: '444 Pet St, Charlotte, NC',
    notes: 'Dog walker',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Jack',
    lastName: 'Jenkins',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 333-4445' }],
    emails: [{ id: generateId(), label: 'home', email: 'jack.jenkins@email.com' }],
    company: '',
    address: '555 BBQ Rd, Houston, TX',
    notes: 'BBQ master',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Kim',
    lastName: 'Perry',
    phones: [{ id: generateId(), label: 'work', number: '(555) 444-5556' }],
    emails: [{ id: generateId(), label: 'work', email: 'kim.perry@ux.com' }],
    company: 'UX Design Studio',
    address: '666 Design Dr, Brooklyn, NY',
    notes: 'UX designer',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Leo',
    lastName: 'Foster',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 555-6667' }],
    emails: [{ id: generateId(), label: 'home', email: 'leo.foster@email.com' }],
    company: '',
    address: '777 Chess Club, St. Louis, MO',
    notes: 'Chess champion',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Mia',
    lastName: 'Pierce',
    phones: [{ id: generateId(), label: 'iphone', number: '(555) 666-7778' }],
    emails: [{ id: generateId(), label: 'icloud', email: 'mia.pierce@icloud.com' }],
    company: 'Dance Academy',
    address: '888 Dance St, Las Vegas, NV',
    notes: 'Dance instructor',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Nick',
    lastName: 'Ramsey',
    phones: [{ id: generateId(), label: 'work', number: '(555) 777-8889' }],
    emails: [{ id: generateId(), label: 'work', email: 'nick.ramsey@network.com' }],
    company: 'Network Solutions',
    address: '999 Server Farm, Ashburn, VA',
    notes: 'Network engineer',
    isFavorite: false,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: generateId(),
    firstName: 'Olivia',
    lastName: 'Sullivan',
    phones: [{ id: generateId(), label: 'mobile', number: '(555) 888-9990' }],
    emails: [{ id: generateId(), label: 'home', email: 'olivia.sullivan@email.com' }],
    company: '',
    address: '111 Coffee Shop, Seattle, WA',
    notes: 'Coffee tasting group',
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const createSampleContacts = (): Contact[] => {
  return sampleContacts;
};
